spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/backendspring
    username: postgres
    password: syspass
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 5MB
