spring:                      //upload file to backend
  datasource:
    url: jdbc.postgres://localhost:5432/springbackend
    username: postgres
    password: aom_31433310
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 5MB

//config connecting to database

